# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SAM IT Solutions
    url: https://samitsolutions.com
  - name: Plesk 2
    url: https://plesk2.samitsolutions.com
    port: 8443
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Broken Site Yes
    url: itsrlybroken1.ksa
  - name: asliceofthecloud
    url: asliceofthecloud.com
  - name: basketballmyworld
    url: basketballmyworld.com
  - name: bikanerelectrical
    url: bikanerelectrical.com
  - name: biryanimaxx
    url: biryanimaxx.com
  - name: carolinaretinaeyecare
    url: carolinaretinaeyecare.com
  - name: caryendoscopycenter
    url: caryendoscopycenter.com
  - name: caryinternalmedicine
    url: caryinternalmedicine.com
  - name: centerfordigestivediseases
    url: centerfordigestivediseases.com
  - name: cholanad
    url: cholanad.com
  - name: civentichem
    url: civentichem.com
  - name: clearpointhealth
    url: clearpointhealth.com
  - name: clovencardamom
    url: clovencardamom.com
  - name: dev.patagoniahealth
    url: dev.patagoniahealth.com
  - name: directed-vr
    url: directed-vr.com
  - name: docnc
    url: docnc.org
  - name: guruindiancuisine
    url: guruindiancuisine.com
  - name: hcilcode
    url: hcilcode.com
  - name: imcs
    url: imcs.sx 
  - name: laysciences
    url: laysciences.com
  - name: monsoonindiancuisine
    url: monsoonindiancuisine.com
  - name: patagoniahealth
    url: patagoniahealth.com
  - name: prdbi
    url: prdbi.com
  - name: rahul-priyadarshi
    url: rahul-priyadarshi.net
  - name: samanalyticsolutions
    url: samanalyticsolutions.com
  - name: samitsolutions
    url: samitsolutions.com
  - name: tandoorchapelhill
    url: tandoorchapelhill.com
  - name: temoacloud
    url: temoacloud.com
  - name: zaykaraleigh
    url: zaykaraleigh.com
    
    
    
    



  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
